In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,4,3], [2,1,3,4]])

In [3]:
a.shape

(2, 4)

In [4]:
type(a)

numpy.ndarray

In [5]:
np.random.random((2,2))

array([[0.9034774 , 0.63548661],
       [0.87619873, 0.31469526]])

In [6]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [7]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.full((2,2), 7) 

array([[7, 7],
       [7, 7]])

## Indexing

In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [11]:
# integer indexing
a[:2, 1:3]

array([[2, 3],
       [6, 7]])

In [12]:
# boolean indexing
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Broadcasting

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

## Reshaping

In [13]:
# flattens array
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
a.shape

(3, 4)

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
# in reshape, -1 means it automatically adjusts the shape
a.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Sorting

In [17]:
a = np.array([[1,2,4,3], [2,1,3,4]])
a

array([[1, 2, 4, 3],
       [2, 1, 3, 4]])

In [18]:
# column wise
np.sort(a, axis=0)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [19]:
# row wise
np.sort(a, axis=1)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [20]:
# inplace sorting
a.sort(axis=0)
a

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

## Aggrigate Functions

In [21]:
a.sum(axis=0)

array([3, 3, 7, 7])

In [22]:
a.max(axis=1)

array([3, 4])

In [23]:
a.mean()

2.5

## Arg Functions

In [24]:
# get the index of max element
a.argmax(axis=1)

array([2, 2])

## Deep and Shallow copy

In [25]:
# shallow copy
b = a

In [26]:
# deep copy
b = a.copy()